package datastructures.collections.automatic_test;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Random;
import java.util.Set;
import datastructures.collections.map.LMapIntToLong;
import datastructures.collections.map.MapIntToLong;
import datastructures.collections.map.MapIntToLong.EntryIterator;
import datastructures.collections.map.MapIntToLong.MapEntryIntToLong;
public class MainTestLMapIntToLong {
	public static void main(String[] args) {
		for (int bucketCount = 1; bucketCount <= 100; bucketCount++) {
			runExperiment(bucketCount);
		}
	}
	private static void runExperiment(int bucketCount) {
		MapIntToLong hashMap = new LMapIntToLong(bucketCount);
		System.out.println("MAP size = " + hashMap.size());
		CheckResults.checkResult(hashMap.size() == 0);
		CheckResults.checkResult(hashMap.isEmpty() == true);
		System.out.println("ADD 1, 10");
		hashMap.put(1, 10);
		CheckResults.checkResult(hashMap.size() == 1);
		CheckResults.checkResult(hashMap.containsKey(1));
		CheckResults.checkResult(hashMap.get(1) == 10);
		System.out.println("ADD 2, 20");
		hashMap.put(2, 20);
		CheckResults.checkResult(hashMap.size() == 2);
		CheckResults.checkResult(hashMap.containsKey(2));
		CheckResults.checkResult(hashMap.get(2) == 20);
		System.out.println("ADD 3, 30");
		hashMap.put(3, 30);
		CheckResults.checkResult(hashMap.containsKey(3));
		CheckResults.checkResult(hashMap.get(3) == 30);
		CheckResults.checkResult(hashMap.size() == 3);
		System.out.println("ADD 4, 10");
		hashMap.put(4, 40);
		CheckResults.checkResult(hashMap.size() == 4);
		CheckResults.checkResult(hashMap.containsKey(4));
		CheckResults.checkResult(hashMap.get(4) == 40);
		System.out.println("ADD 5, 20");
		hashMap.put(5, 50);
		CheckResults.checkResult(hashMap.size() == 5);
		CheckResults.checkResult(hashMap.containsKey(5));
		CheckResults.checkResult(hashMap.get(5) == 50);
		System.out.println("ADD 6, 20");
		hashMap.put(6, 60);
		CheckResults.checkResult(hashMap.size() == 6);
		CheckResults.checkResult(hashMap.containsKey(6));
		CheckResults.checkResult(hashMap.get(6) == 60);
		System.out.println("MAP size = " + hashMap.size());
		System.out.println("Value for key 1: " + hashMap.get(1));
		System.out.println("Value for key 2: " + hashMap.get(2));
		System.out.println("Value for key 3: " + hashMap.get(3));
		System.out.println("Value for key 4: " + hashMap.get(4));
		System.out.println("Value for key 5: " + hashMap.get(5));
		System.out.println("Value for key 6: " + hashMap.get(6));
		System.out.println("MAP size = " + hashMap.size());
		System.out.println("MAP size = " + hashMap.size());
		System.out.println("ADD 1, 100");
		hashMap.put(1, 100);
		System.out.println("ADD 2, 200");
		hashMap.put(2, 200);
		System.out.println("ADD 3, 300");
		hashMap.put(3, 300);
		System.out.println("ADD 4, 400");
		hashMap.put(4, 400);
		System.out.println("ADD 5, 500");
		hashMap.put(5, 500);
		System.out.println("ADD 6, 600");
		hashMap.put(6, 600);
		System.out.println("MAP size = " + hashMap.size());
		System.out.println("Value for key 1: " + hashMap.get(1));
		System.out.println("Value for key 2: " + hashMap.get(2));
		System.out.println("Value for key 3: " + hashMap.get(3));
		System.out.println("Value for key 4: " + hashMap.get(4));
		System.out.println("Value for key 5: " + hashMap.get(5));
		System.out.println("Value for key 6: " + hashMap.get(6));
		System.out.println("MAP size = " + hashMap.size());
		CheckResults.checkResult(hashMap.containsKey(1));
		CheckResults.checkResult(hashMap.containsKey(2));
		CheckResults.checkResult(hashMap.containsKey(3));
		CheckResults.checkResult(hashMap.containsKey(4));
		CheckResults.checkResult(hashMap.containsKey(5));
		CheckResults.checkResult(hashMap.containsKey(6));
		CheckResults.checkResult(hashMap.get(1) == 100);
		CheckResults.checkResult(hashMap.get(2) == 200);
		CheckResults.checkResult(hashMap.get(3) == 300);
		CheckResults.checkResult(hashMap.get(4) == 400);
		CheckResults.checkResult(hashMap.get(5) == 500);
		CheckResults.checkResult(hashMap.get(6) == 600);
		CheckResults.checkResult(hashMap.size() == 6);
		System.out.println("REMOVE 1");
		hashMap.remove(1);
		System.out.println("Value for key 1: " + hashMap.get(1));
		System.out.println("Value for key 2: " + hashMap.get(2));
		System.out.println("Value for key 3: " + hashMap.get(3));
		System.out.println("Value for key 4: " + hashMap.get(4));
		System.out.println("Value for key 5: " + hashMap.get(5));
		System.out.println("Value for key 6: " + hashMap.get(6));
		System.out.println("MAP size = " + hashMap.size());
		CheckResults.checkResult(hashMap.containsKey(1) == false);
		CheckResults.checkResult(hashMap.containsKey(2));
		CheckResults.checkResult(hashMap.containsKey(3));
		CheckResults.checkResult(hashMap.containsKey(4));
		CheckResults.checkResult(hashMap.containsKey(5));
		CheckResults.checkResult(hashMap.containsKey(6));
		CheckResults.checkResult(hashMap.get(1) == -1);
		CheckResults.checkResult(hashMap.get(2) == 200);
		CheckResults.checkResult(hashMap.get(3) == 300);
		CheckResults.checkResult(hashMap.get(4) == 400);
		CheckResults.checkResult(hashMap.get(5) == 500);
		CheckResults.checkResult(hashMap.get(6) == 600);
		CheckResults.checkResult(hashMap.size() == 5);
		System.out.println("REMOVE 2");
		hashMap.remove(2);
		System.out.println("Value for key 1: " + hashMap.get(1));
		System.out.println("Value for key 2: " + hashMap.get(2));
		System.out.println("Value for key 3: " + hashMap.get(3));
		System.out.println("Value for key 4: " + hashMap.get(4));
		System.out.println("Value for key 5: " + hashMap.get(5));
		System.out.println("Value for key 6: " + hashMap.get(6));
		System.out.println("MAP size = " + hashMap.size());
		CheckResults.checkResult(hashMap.containsKey(1) == false);
		CheckResults.checkResult(hashMap.containsKey(2) == false);
		CheckResults.checkResult(hashMap.containsKey(3));
		CheckResults.checkResult(hashMap.containsKey(4));
		CheckResults.checkResult(hashMap.containsKey(5));
		CheckResults.checkResult(hashMap.containsKey(6));
		CheckResults.checkResult(hashMap.get(1) == -1);
		CheckResults.checkResult(hashMap.get(2) == -1);
		CheckResults.checkResult(hashMap.get(3) == 300);
		CheckResults.checkResult(hashMap.get(4) == 400);
		CheckResults.checkResult(hashMap.get(5) == 500);
		CheckResults.checkResult(hashMap.get(6) == 600);
		CheckResults.checkResult(hashMap.size() == 4);
		System.out.println("REMOVE 6");
		hashMap.remove(6);
		System.out.println("MAP size = " + hashMap.size());
		System.out.println("Value for key 1: " + hashMap.get(1));
		System.out.println("Value for key 2: " + hashMap.get(2));
		System.out.println("Value for key 3: " + hashMap.get(3));
		System.out.println("Value for key 4: " + hashMap.get(4));
		System.out.println("Value for key 5: " + hashMap.get(5));
		System.out.println("Value for key 6: " + hashMap.get(6));
		System.out.println("MAP size = " + hashMap.size());
		CheckResults.checkResult(hashMap.containsKey(1) == false);
		CheckResults.checkResult(hashMap.containsKey(2) == false);
		CheckResults.checkResult(hashMap.containsKey(3));
		CheckResults.checkResult(hashMap.containsKey(4));
		CheckResults.checkResult(hashMap.containsKey(5));
		CheckResults.checkResult(hashMap.containsKey(6) == false);
		CheckResults.checkResult(hashMap.get(1) == -1);
		CheckResults.checkResult(hashMap.get(2) == -1);
		CheckResults.checkResult(hashMap.get(3) == 300);
		CheckResults.checkResult(hashMap.get(4) == 400);
		CheckResults.checkResult(hashMap.get(5) == 500);
		CheckResults.checkResult(hashMap.get(6) == -1);
		CheckResults.checkResult(hashMap.size() == 3);
		System.out.println("Contains key 1?: " + hashMap.containsKey(1));
		System.out.println("Contains key 2?: " + hashMap.containsKey(2));
		System.out.println("Contains key 3?: " + hashMap.containsKey(3));
		System.out.println("Contains key 4?: " + hashMap.containsKey(4));
		System.out.println("Contains key 5?: " + hashMap.containsKey(5));
		System.out.println("Contains key 6?: " + hashMap.containsKey(6));
		System.out.println("ADD 1, 1000");
		hashMap.put(1, 1000);
		System.out.println("ADD 2, 2000");
		hashMap.put(2, 2000);
		System.out.println("ADD 6, 6000");
		hashMap.put(6, 6000);
		CheckResults.checkResult(hashMap.containsKey(1) == true);
		CheckResults.checkResult(hashMap.containsKey(2) == true);
		CheckResults.checkResult(hashMap.containsKey(3));
		CheckResults.checkResult(hashMap.containsKey(4));
		CheckResults.checkResult(hashMap.containsKey(5));
		CheckResults.checkResult(hashMap.containsKey(6) == true);
		CheckResults.checkResult(hashMap.get(1) == 1000);
		CheckResults.checkResult(hashMap.get(2) == 2000);
		CheckResults.checkResult(hashMap.get(3) == 300);
		CheckResults.checkResult(hashMap.get(4) == 400);
		CheckResults.checkResult(hashMap.get(5) == 500);
		CheckResults.checkResult(hashMap.get(6) == 6000);
		CheckResults.checkResult(hashMap.size() == 6);
		CheckResults.checkResult(hashMap.isEmpty() == false);
		System.out.println("Value for key 1: " + hashMap.get(1));
		System.out.println("Value for key 2: " + hashMap.get(2));
		System.out.println("Value for key 3: " + hashMap.get(3));
		System.out.println("Value for key 4: " + hashMap.get(4));
		System.out.println("Value for key 5: " + hashMap.get(5));
		System.out.println("Value for key 6: " + hashMap.get(6));
		System.out.println("MAP size = " + hashMap.size());
		System.out.println("Contains key 1?: " + hashMap.containsKey(1));
		System.out.println("Contains key 2?: " + hashMap.containsKey(2));
		System.out.println("Contains key 3?: " + hashMap.containsKey(3));
		System.out.println("Contains key 4?: " + hashMap.containsKey(4));
		System.out.println("Contains key 5?: " + hashMap.containsKey(5));
		System.out.println("Contains key 6?: " + hashMap.containsKey(6));
		System.out.println("ITERATING OVER THE KEY,VALUES");
		EntryIterator iter = hashMap.iterator();
		Set<MapEntryIntToLong> hashSetResults = new HashSet<>();
		int count = 0;
		while (iter.hasNext()) {
			MapEntryIntToLong node = iter.next();
			hashSetResults.add(node);
			System.out.println("  Entry :" + node.getKey() + " " + node.getValue());
			count++;
			if (count < 6) {
				CheckResults.checkResult(iter.hasNext() == true);
			} else {
				CheckResults.checkResult(iter.hasNext() == false);
			}
		}
		CheckResults.checkResult(hashSetResults.size() == 6);
		System.out.println("ITERATING OVER THE KEY,VALUES");
		EntryIterator iter2 = hashMap.iterator();
		Set<MapEntryIntToLong> hashSetResults2 = new HashSet<>();
		int count2 = 0;
		while (iter2.hasNext()) {
			MapEntryIntToLong node = iter2.next();
			count2++;
			if (count2 == 1 || count2 == 3) {
				System.out.println("  Removing entry :" + node.getKey() + " " + node.getValue());
				iter2.remove();
			} else {
				System.out.println("  Entry :" + node.getKey() + " " + node.getValue());
				hashSetResults2.add(node);
			}
			if (count2 < 6) {
				CheckResults.checkResult(iter2.hasNext() == true);
			} else {
				CheckResults.checkResult(iter2.hasNext() == false);
			}
		}
		CheckResults.checkResult(hashSetResults2.size() == 4);
		System.out.println("ITERATING OVER THE KEY,VALUES");
		EntryIterator iter3 = hashMap.iterator();
		Set<MapEntryIntToLong> hashSetResults3 = new HashSet<>();
		int count3 = 0;
		while (iter3.hasNext()) {
			MapEntryIntToLong node3 = iter3.next();
			hashSetResults3.add(node3);
			System.out.println("  Entry :" + node3.getKey() + " " + node3.getValue());
			count3++;
			if (count3 < 4) {
				CheckResults.checkResult(iter3.hasNext() == true);
			} else {
				CheckResults.checkResult(iter3.hasNext() == false);
			}
		}
		CheckResults.checkResult(hashSetResults3.size() == 4);
		System.out.println("CLEARING THE MAP");
		hashMap.clear();
		CheckResults.checkResult(hashMap.isEmpty() == true);
		CheckResults.checkResult(hashMap.size() == 0);
		CheckResults.checkResult(hashMap.containsKey(1) == false);
		CheckResults.checkResult(hashMap.containsKey(2) == false);
		CheckResults.checkResult(hashMap.containsKey(3) == false);
		CheckResults.checkResult(hashMap.containsKey(4) == false);
		CheckResults.checkResult(hashMap.containsKey(5) == false);
		CheckResults.checkResult(hashMap.containsKey(6) == false);
		System.out.println("WE DO AN ITERATOR ON AN EMPTY MAP");
		EntryIterator iter4 = hashMap.iterator();
		CheckResults.checkResult(iter4.hasNext() == false);
		CheckResults.checkResult(hashMap.size() == 0);
		CheckResults.checkResult(hashMap.isEmpty() == true);
		System.out.println("OK.");
		System.out.println("ADD 9, 90");
		hashMap.put(9, 90);
		CheckResults.checkResult(hashMap.size() == 1);
		CheckResults.checkResult(hashMap.containsKey(9));
		CheckResults.checkResult(hashMap.get(9) == 90);
		System.out.println("WE DO AN ITERATOR ON THAT MAP");
		EntryIterator iter5 = hashMap.iterator();
		MapEntryIntToLong x = iter5.next();
		System.out.println(" It contains : " + x.getKey() + " , " + x.getValue());
		CheckResults.checkResult(x.getKey() == 9 && x.getValue() == 90);
		CheckResults.checkResult(iter5.hasNext() == false);
		CheckResults.checkResult(hashMap.size() == 1);
		CheckResults.checkResult(hashMap.isEmpty() == false);
		System.out.println("WE DO AN ITERATOR AGAIN ON THAT MAP");
		EntryIterator iter6 = hashMap.iterator();
		MapEntryIntToLong x6 = iter6.next();
		System.out.println(" It contains : " + x6.getKey() + " , " + x6.getValue());
		CheckResults.checkResult(x6.getKey() == 9 && x6.getValue() == 90);
		CheckResults.checkResult(iter6.hasNext() == false);
		CheckResults.checkResult(hashMap.size() == 1);
		CheckResults.checkResult(hashMap.isEmpty() == false);
		System.out.println("Now remove the current entry from the map");
		iter6.remove();
		CheckResults.checkResult(iter6.hasNext() == false);
		CheckResults.checkResult(iter6.hasNext() == false);
		CheckResults.checkResult(hashMap.size() == 0);
		CheckResults.checkResult(hashMap.size() == 0);
		CheckResults.checkResult(hashMap.isEmpty() == true);
		CheckResults.checkResult(hashMap.isEmpty() == true);
		System.out.println("The map is empty, and hasNext = " + iter6.hasNext());
		hashMap.clear();
		CheckResults.checkResult(hashMap.isEmpty() == true);
		CheckResults.checkResult(hashMap.size() == 0);
		HashMap<Integer, Integer> mirror = new HashMap<Integer, Integer>();
		Random rand = new Random(System.currentTimeMillis());
		int i = 0;
		while (i < 50) {
			int randomNumber = rand.nextInt(100) + 1;
			hashMap.put(randomNumber, randomNumber + 1);
			mirror.put(randomNumber, randomNumber + 1);
			i++;
			CheckResults.checkResult(hashMap.size() == mirror.size());
			CheckResults.checkResult(hashMap.get(randomNumber) == mirror.get(randomNumber));
		}
		System.out.println(hashMap.size());
		i = 0;
		while (i < 10) {
			int randomNumber = rand.nextInt(100) + 1;
			hashMap.remove(randomNumber);
			mirror.remove(randomNumber);
			i++;
			CheckResults.checkResult(hashMap.size() == mirror.size());
			CheckResults.checkResult(hashMap.get(randomNumber) == -1);
		}
		System.out.println(hashMap.size());
		MapIntToLong hashMap2 = new LMapIntToLong(bucketCount);
		System.out.println("MAP size = " + hashMap2.size());
		CheckResults.checkResult(hashMap2.size() == 0);
		CheckResults.checkResult(hashMap2.isEmpty() == true);
		System.out.println("ADD 1, 10");
		hashMap2.put(1,  10);
		CheckResults.checkResult(hashMap2.size() == 1);
		CheckResults.checkResult(hashMap2.containsKey(1));
		CheckResults.checkResult(hashMap2.get(1) == 10);
		System.out.println("ADD 2, 20");
		hashMap2.put(2,  20);
		CheckResults.checkResult(hashMap2.size() == 2);
		CheckResults.checkResult(hashMap2.containsKey(2));
		CheckResults.checkResult(hashMap2.get(2) == 20);
		System.out.println("CHANGE VALUE OF KEY 2  TO :   20 + 5 = 25");
		hashMap2.getAndIncreaseValueBy(2,  5);
		CheckResults.checkResult(hashMap2.containsKey(2));
		CheckResults.checkResult(hashMap2.get(1) == 10);
		CheckResults.checkResult(hashMap2.get(2) == 25);
		System.out.println("CHANGE VALUE OF KEY 2  TO :   25 + 5 = 30");
		System.out.println("CHANGE VALUE OF KEY 1  TO :   10 + 2 = 12");
		hashMap2.getAndIncreaseValueBy(1,  2);
		hashMap2.getAndIncreaseValueBy(2,  5);
		CheckResults.checkResult(hashMap2.size() == 2);
		CheckResults.checkResult(hashMap2.containsKey(1));
		CheckResults.checkResult(hashMap2.containsKey(2));
		CheckResults.checkResult(hashMap2.get(1) == 12);
		CheckResults.checkResult(hashMap2.get(2) == 30);
		hashMap2.getAndIncreaseValueBy(3,  33);
		hashMap2.getAndIncreaseValueBy(4,  44);
		CheckResults.checkResult(hashMap2.size() == 4);
		CheckResults.checkResult(hashMap2.containsKey(1));
		CheckResults.checkResult(hashMap2.containsKey(2));
		CheckResults.checkResult(hashMap2.containsKey(3));
		CheckResults.checkResult(hashMap2.containsKey(4));
		CheckResults.checkResult(hashMap2.get(1) == 12);
		CheckResults.checkResult(hashMap2.get(2) == 30);
		CheckResults.checkResult(hashMap2.get(3) == 33);
		CheckResults.checkResult(hashMap2.get(4) == 44);
		datastructures.collections.map.MapIntToLong.ValueIterator iterVal = hashMap2.iteratorForValues();
		Set setValues = new HashSet<Integer>();
		while (iterVal.hasNext()) {
			long value = iterVal.next();
			System.out.println("Value : " + value);
			setValues.add(value);
		}
		CheckResults.checkResult(setValues.contains(12l));
		CheckResults.checkResult(setValues.contains(30l));
		CheckResults.checkResult(setValues.contains(33l));
		CheckResults.checkResult(setValues.contains(44l));
		CheckResults.checkResult(setValues.size()==4);
		datastructures.collections.map.MapIntToLong.KeyIterator iterKey = hashMap2.iteratorForKeys();
		Set setKeys = new HashSet<Integer>();
		while (iterKey.hasNext()) {
			int key = iterKey.next();
			System.out.println("key : " + key);
			setKeys.add(key);
		}
		CheckResults.checkResult(setKeys.contains(1));
		CheckResults.checkResult(setKeys.contains(2));
		CheckResults.checkResult(setKeys.contains(3));
		CheckResults.checkResult(setKeys.contains(4));
		CheckResults.checkResult(setKeys.size()==4);
	}
}

